import { router } from "@trpc/server";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React, { useState } from "react";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const subscribe = api.subscription.subscribe.useMutation();
  const [form, setForm] = useState({ email: '' })
  const router = useRouter()

  // TODO: red email alerts / validation
  async function handleSubscribe(e: React.FormEvent) {
    e.preventDefault()
    await subscribe.mutateAsync({
      email: form.email,
    })
    router.push('/success')
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-4 bg-gray-700 min-h-screen items-center justify-center">
        <h1 className="text-4xl font-bold">WebDevCody Newsletter</h1>
        <p>Enter your email below to receive updates and various news.</p>
        <form onSubmit={handleSubscribe} className="flex flex-col gap-4">
          <label htmlFor="email">Email</label>
          <input
            onChange={(e) => setForm({ email: e.target.value })}
            className="input w-full max-w-xs input-bordered input-info" id="email"></input>
          <button className="btn btn-primary">Subscribe</button>
        </form>
      </main>
    </>
  );
};

export default Home;
