import { type NextPage } from "next";
import Head from "next/head";

const SuccessPage: NextPage = () => {

  return (
    <>
      <Head>
        <title>Subscribed</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-4 bg-gray-700 min-h-screen items-center justify-center">
        <h1>Successfully subscribed</h1>
      </main>
    </>
  );
};

export default SuccessPage;
