import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { useUnsubscribe } from "../../api/useUnsubscribe";

const Home: NextPage = () => {
  const { unsubscribe } = useUnsubscribe();
  const [status, setStatus] = useState("unsubscribing...");

  const router = useRouter();
  const unsubscribeId = router.query.unsubscribeId as string;

  useEffect(() => {
    if (!unsubscribeId) return;
    unsubscribe(unsubscribeId)
      .then(() => {
        setStatus("successfully unsubscribed!");
      })
      .catch(() => {
        // TODO:
      });
  }, [unsubscribe, unsubscribeId]);

  return (
    <>
      <Head>
        <title>Unsubscribe</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-4">
        <span data-testid="unsubscribe-status">{status}</span>
      </main>
    </>
  );
};

export default Home;
