import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { api } from "../../utils/api";


const Home: NextPage = () => {
  const { mutateAsync: unsubscribe } = api.subscription.unsubscribe.useMutation()
  const [status, setStatus] = useState('unsubscribing...')

  const router = useRouter()
  const email = router.query.email as string

  useEffect(() => {
    if (!email) return;
    console.log('email', email)
    unsubscribe({
      email,
    }).then(() => {
      setStatus('successfully unsubscribed!');
    })
  }, [unsubscribe, email])

  return (
    <>
      <Head>
        <title>Unsubscribe</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-4 bg-gray-700 min-h-screen items-center justify-center">
        {status}
      </main>
    </>
  );
};

export default Home;
