import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { api } from "../../utils/api";

const Home: NextPage = () => {
  const { mutateAsync: unsubscribe } =
    api.subscription.unsubscribe.useMutation();
  const [status, setStatus] = useState("unsubscribing...");

  const router = useRouter();
  const unsubscribeId = router.query.unsubscribeId as string;

  useEffect(() => {
    if (!unsubscribeId) return;
    unsubscribe({
      unsubscribeId,
    })
      .then(() => {
        setStatus("successfully unsubscribed!");
      })
      .catch(() => {
        // TODO:
      });
  }, [unsubscribe, unsubscribeId]);

  return (
    <>
      <Head>
        <title>Unsubscribe</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-4">
        {status}
      </main>
    </>
  );
};

export default Home;
